### ISSUE TITLE
always have a selected Template?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#126]
The behavior of the Template Config buttons are confusing if there is no Template selected.  It lacks feedback when a button is pressed but no action occurs because no Template is selected. 

Could the list of Templates be changed so that (like a People view) a row is ALWAYS selected... initializing to the Active template being selected?  (List views, like the People view, allow extended selections. This dialog should allow one and only one selected item.) Such a requirement would both eliminate the ambiguity and the need to explain that that a row must be selected for the feature to work. 

Gramps moves the "Active" focus with the selection in most parts of the GUI.  Let's not use "Active Template"  How about using Radio Buttons in that column and using them to eliminate the "Make Active" button. Or, if they can be layered, use Ordering buttons and checkboxes? Then the 1st column can be "Order" or "Priority"

There is a delay between clicking the "Edit Template" and the dialog appearing. This makes it too easy to open 2 template editors for the same template. (I can see a possible use for having editors for different templates open for reference. But 2 editors for the same template seems like a conflict waiting to happen.) If more than one Template editor is open, there ought to be some indicator in whichever is the Active Template.

Also, for neatness sake, please store the templates in their own folder.  The subfolder could be in the parent folder of the plugins folder or a sub-folder where they are now dumped: the gramps51 folder of the User Directory.

**Comment by cdhorn** [comment]
I think this is working a bit better now.  Check box used for active, button removed, startup and subsequent selection tracks better, window tracking is working, and you are now restricted to one edit session per template.

I think Active is the correct name, one and only one can ever be active. 

I did not move the templates yet, I'm unsure if there is a particular location @Nick-Hall thinks is suitable.

**Comment by emyoulation** [comment]
Do you think there's room in this template feature for swapping Gramplet splitbar collections?

I'm not sure which Gramplets go well with which views.. but I expect the optimal set will be different when in a data-entry session vs. an analysis or exploration session.

It it is a good approach, maybe @Nick-Hall could adopt it for the dashboard? I'd love to have a Newbie Dashboard, a Database health dashboard, a Tree Stats dashboard, et cetera ad nauseum.

**Comment by Nick-Hall** [comment]
Having different dashboard setups for different purposes is a good idea.  I'm not sure how it relates to this plugin though.

**Comment by emyoulation** [comment]
> Having different dashboard setups for different purposes is a good idea. I'm not sure how it relates to this plugin though.

It relates through the new preference Templating functionality that Chris just layered into the LinkedView/BrowseView.

He is creating an entire new layer of .ini files in the Gramps51 folder. And while his layers are related to the data presentation customizations of his View, the standard Gramps .ini files for the views & splitbar could potentially be rolled into a similar template manager. So my first inquiry was about compatibility of LinkedView Gramplet splitbar .ini management options in the LinkedView template feature.

Then, since the Dashboard is the testbed for Gramplet management, extending the concept to all views would probably start with there. 

It seemed like evaluation and feedback from the architect (with an eye toward this potential FUTURE! expansion) could avoid (a few) conflicts down the line.

Of particular concern, storage of 3 .ini files for every View is already cluttering up the Gramps51 folder. Storing (a potentially unlimited number of) template variants at that level of the Gramps addons installation could slow down OS access to all the subfolders. 

Windoze has a (perennially toted as fixed, but not TRULY fixed) performance hit when 255 files per folder is exceeded.

The .ini management of the Add-ons is already messy & inconsistent. Some store them in the gramps51 folder, some in the Gramps51/plugin subfolder, some in user defined locations.

**Comment by emyoulation** [comment]
@Nick-Hall  
The aspect of the Templates management is that Chris recently converted this add-on from a Relationships view mode to an entirely new View.

So what was an inconvenience before (where the Gramplets that were metaphorically incompatible with the content as the Active Object type focus changed) may be become a serious design flaw that has to be addressed.

One (ugly) way of mitigating that would be to have Splitbar Gramplet collection change as the Active Object type context changes... possibly via the context change being communicated to his template manager.

**Comment by cdhorn** [comment]
Closing this too as always has a default selected.
