### ISSUE TITLE
ReadMe.md change

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#130]
Please update the documentation to reflect that this is no longer a Relationships view mode but and entire new category in the interface.

BTW, the remnants left behind have been persistent. And, even with the 5.1.5 update, my Gramps was crashing when I switched to the Relationships view category the 1st time. 

I had to manually clean out all the relationship & Linked .ini files and the gramps.ini file subsection before it stabilized. Perhaps you could provide some suggestions to the Core team on the registration and ini evaluation? 

If an add-on hasn't been installed (or has been moved or disabled) then Gramps should not fail because of persistent configuration remnants. At the very least, there should be some sort of cleaning tools that strips config items that were skipped because they cannot validate. Some of the items I manually stripped had not been valid since the 1st weeks of your add-on. 

The same thing happens with window positions in Gramps. Paul fixed the problem where Windows tacked to a 2nd screen were off-screen when you switched back to a single monitor configuration. But, unless you manually reposition or resize the window, the next time the 2nd monitor is available, it goes back there. So Gramps was doing that extra validate & fallback step every time a bunch of my window popped up. And I had no idea. 

Unfortunately, the critical function configuration items (like the folders paths, default database folder, ID presets, and backup settings) are not separate from the convenience settings (like window positions, Gramplet sets, & column orders). So users cannot just safely flush the Gramps User Directory. That mix is going to make a cleanup tool necessary sometime in the future.

**Comment by cdhorn** [comment]
> Please update the documentation to reflect that this is no longer a Relationships view mode but and entire new category in the interface.

Agree I need to do so.  I am thinking I should rename it yet again to BrowseView to align with the new category.

> BTW, the remnants left behind have been persistent. And, even with the 5.1.5 update, my Gramps was crashing when I switched to the Relationships view category the 1st time.

This plugin should no longer be appearing under the Relationships category.  Do you still have an older as well as newer version installed in your plugins directory at the same time?

> I had to manually clean out all the relationship & Linked .ini files and the gramps.ini file subsection before it stabilized. Perhaps you could provide some suggestions to the Core team on the registration and ini evaluation?

> If an add-on hasn't been installed (or has been moved or disabled) then Gramps should not fail because of persistent configuration remnants. At the very least, there should be some sort of cleaning tools that strips config items that were skipped because they cannot validate. Some of the items I manually stripped had not been valid since the 1st weeks of your add-on.

I guess I'm having trouble following you here. Yes the options and options handling have changed many times, but this hasn't been submitted for inclusion yet so that is/was to be expected, especially after refactoring to support option templates.

**Comment by cdhorn** [comment]
README updated extensively, closing this.
