### ISSUE TITLE
CardView (VERSION = "0.92") a few [ AttributeError: 'NoneType' object has no attribute .... ]

### ISSUE THREAD

**Issue by wroldwiedbwe** [cdhorn/CardView#135]
Love the new name and how you have moved the card views into the individual category views 🥇 Thank you 👍  

Using a Brand new Gramps 5.1.5 portable AIO installation with the example.gramps family tree and CardView (VERSION = "0.92")

- [x] Select the "Tags" category view  ( this category list/view when it works looks to be very handy to me as I literally have a ton of tags! Current  no tags are listed/shown although example.gramps has them.)

Select the "**Pin a copy of current view in another window**" icon

and I get the following error:

> 285848: ERROR: grampsapp.py: line 174: Unhandled exception
> Traceback (most recent call last):
>   File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 591, in launch_view_window
>     windows.launch_view_window(self.grstate, self.current_context)
>   File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\services\service_windows.py", line 195, in launch_view_window
>     key = grcontext.obj_key
> AttributeError: 'NoneType' object has no attribute 'obj_key'
> 

-------------------------------------
- [x] Same Tags category view

Select either of the **"Edit the active tag"** or  **"Delete the active tag"** icon and get:

> 739222: ERROR: grampsapp.py: line 174: Unhandled exception
> Traceback (most recent call last):
>   File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 675, in edit_active
>     active_object = self.current_context.primary_obj
> AttributeError: 'NoneType' object has no attribute 'primary_obj'
> 

--------------
- [x] Also each of the category card view icons are only displaying a grey warning triangle?

**Comment by cdhorn** [comment]
Thank you for the feedback and bug report!

> this category list/view when it works looks to be very handy to me as I literally have a ton of tags! Current no tags are listed/shown although example.gramps has them

There is currently no tags list view as I mentioned in the README. Maybe I will look at adding a simple one. There is so little to a tag they are not really treated as primary objects in Gramps although they have handles. So in that sense the organize tags tool has probably been deemed sufficient.  I kind of needed the category as it felt unnatural to shoehorn the tag page view into any of the others.

Items one and two for sure I will fix later tonight.

Item three looks like it might be related to Windows. I will spin up a VM and check on that as well later.

**Comment by PQYPLZXHGF** [comment]
**I also have this issue (AttributeError: 'NoneType' object has no attribute 'obj_key') but when selecting the "Places" category and then using  "Pin a copy of current view in another window" .**  Happens when you have not selected a place.

Thank you for CardView makes a great addition to Gramps 🙌✨✔ 

Minor point (nitpick, sorry get off my grass 😊)why do you call it the **Card View Plugin** instead of going with what Gramps project calls all external plugins which is  "addons" hopefully you will use with the preferred naming of external plugins?

**Comment by cdhorn** [comment]
Item 1 is fixed, it makes sure there is an active object before trying to spawn.

Item 2 is fixed, both edit and delete work on the Card View Tag page. 

I did not get to item 3 tonight.

I have added a Tag List View.  It is kind of a hack as some things in Gramps core were not happy with it.  The one thing that I know is not fixed is on the pop up menu as I did not have time to figure out what to do with the quick view options.

Regarding plugin and addon yes I kind of use them interchangeably which I probably shouldn't do.

**Comment by wroldwiedbwe** [comment]
> I have added a Tag List View.

You're wonderful, extremely helpful 😎, 

do we need to convince the Gramps team to make tags primary objects?  

Thank you,

**Comment by cdhorn** [comment]
> do we need to convince the Gramps team to make tags primary objects?

I don't think so as they do not have a Gramps Id nor should they.

**Comment by wroldwiedbwe** [comment]
> Let me know if that resolves the issue with it not rendering the toolbar.

Unfortunately no, but I believe I've worked out what it is with the Grampsportable and was able to test and confirm using the standard Gramps AIO on Windoze!  

The only thing I needed to do was change the filename the addon was extracted to "CardView" instead of "CardView-master" that the extraction program defaults to in this case I was using 7Zip's extract folder here option. Note that using Widows Explorers default "Extract All..." option creates a double depth folder eg  "\CardView-master\CardView-master\"  that if you rename and move the files down one level the icons show correctly in the views.

![Extract Compressed (Zipped) Folders](https://user-images.githubusercontent.com/29416263/170130448-ea689381-4fad-4010-8ddb-3479fb683486.png)


![working-renamed-folder](https://user-images.githubusercontent.com/29416263/170130458-72fa9e76-c72c-49d9-bb05-6fe533a5ec91.png)


I then installed GraphView and renamed its folder and get the same result of a missing icon.

I've only tested on Windows 10 but have no idea if the above is true (renaming the addon folder) at all on other operating systems?


![Graphview-renamedfolder-missingicon-Gramps](https://user-images.githubusercontent.com/29416263/170130455-9e4076e7-2636-47a9-b145-c17d4c22c7b3.png)


So in general the hardcoded addons folder path was the issue and usually as the addons are always download via Gramps with a predicable path nobody would ever see this issue!

**Comment by cdhorn** [comment]
Ah okay that explains it. In `card_view.gpr.py` I do the following for it to find the icon and it is hard coded:
```
fname = os.path.join(USER_PLUGINS, "CardView", "icons")
icons = Gtk.IconTheme().get_default()
icons.append_search_path(fname)
```
Wonder if there is a better way to handle that...

**Comment by cdhorn** [comment]
I think cc65dabc2510b64e0afcb9a008d02566db0b9bd6 will handle that okay now...

**Comment by wroldwiedbwe** [comment]
> I think https://github.com/cdhorn/CardView/commit/cc65dabc2510b64e0afcb9a008d02566db0b9bd6 will handle that okay now...

Works for me. 

I feel this one was a bit misleading as it was nothing to do with your addon!

Thank you 🎉

**Comment by cdhorn** [comment]
That's fine, others ran into it as well and it's a reasonable work around.  Thanks for reporting bugs!

**Comment by daleathan** [comment]
> Item 2 is fixed, both edit and delete work on the Card View Tag page.

@cdhorn Hi, thank you for the addon. Just tried the edit and delete buttons on the Tag Card view with an empty familytree and get the [original error mention above](https://github.com/cdhorn/CardView/issues/135#issue-1244825269) did you accidentally revert the fix?:


_51425: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "D\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 698, in edit_active
    active_object = self.current_context.primary_obj
AttributeError: 'NoneType' object has no attribute 'primary_obj'_


![2022-06-07 14_45_53-empty - Tag - Gramps](https://user-images.githubusercontent.com/1161914/172298452-0b145781-0225-49c9-b326-ec6e10385d82.png)


![2022-06-07 14_51_34-empty - Tag - Gramps](https://user-images.githubusercontent.com/1161914/172298633-c98a7362-ef3e-4745-bd9c-124e55891c1b.png)

**Comment by wroldwiedbwe** [comment]
Yeah forgot to mention that, was happy the other two issue are fixed, I'll make sure to do one bug per issue in future 😢

**Comment by cdhorn** [comment]
Sorry about that guys, that should be fixed now too. I think I fixed the no db open case and forgot the empty db one.
