### ISSUE TITLE
Sidebar & Bottombar defaults

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#136]
Just installed the Cardview add-on... Thanks!

I was having some problems with the default sizes of the gramplet Sidebar & Bottombar (i.e., splitbars) in each view.  Both were "on" by default in each new Card view mode. Since they do not have a default Gramplet, perhaps they could default to being off?

Also the Bottom bar was was just a single row ... except for the very weird Note & Tags view modes where it disconcertingly grabbed 100% of the View window's height. Those defaults which required resizing for every bar and then turning each splitbar off.  The Sidebar grabbed about 75% of the View window's width.

Could you use the same width/height selections that the Relationship view mode has as a fallback/default?

**Comment by cdhorn** [comment]
That was my bad, I should not have had the position vars in the defaults, removed now.

I'll check and see if I can disable the side and bottom bar by default on an initial run, not sure if it is possible. Is probably the case with dashboard as the nav_type is none there but just a guess.

**Comment by cdhorn** [comment]
Decided not going to try to disable the bottom and side bars so going to close this.
