### ISSUE TITLE
Default Nav Gramplet

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#137]
There is implicit inter-category navigation with the Card views: If the card view mode is "Person" then clicking an Event on a card goes to that Category and navigates the Active Record to the clicked record. That order might be the reverse of what actually happens.

And there is Intra-Category navigations using the Go Menu (last Active Record), bookmarks, pinned views, or the Clipboard. (The Forward/Back are more likely to switch category of Active Record.)

But a Gramplet that has a hotlinked list the last 5-10 MODIFIED records in the category would provide: a useful navigation alternative tool, a good default Gramplet, & an intuitive visual prompt when the view is blank because of no active object in category. It would be nice to have a Config for the record count limit & swapping the click/ right-click behavior between navigating & opening the Object Edit dialog.

(It would also help with one of the annoying oversights in Gramps: when you add a new record, it is not added to the Go Menu, the Active record focus does not follow and the new record seems to just... vaporize. Until you learn to sort on Modified Date, it is too easy to lose track of new labor.)

**Comment by cdhorn** [comment]
I started with the LastChange Gramplet as model for this and things are going well. The initial backend service for it is done.

At a minimum the plan is to provide say the last 10 for the category in focus and the last 10 globally for the database.

**Comment by cdhorn** [comment]
Still need to sort some navigation quirks but initial iteration pushed.  I've not tested much on large trees or switching databases, probably more quirks to sort so your mileage may vary!

**Comment by cdhorn** [comment]
And there are options, it has a tabbed mode and some other stuff.

**Comment by emyoulation** [comment]
This is very cool!  

The Global option worried me until I tried it. The overhead prospect of opening each category to repopulate the Global list each time the Gramplet initialized as you switched categories scared me. But it appears that this Gramplet shares data amongst its iterations? So it only needs to poll if the tree has been "Dirty"d, otherwise it load from a common cache? VERY efficient!

The default of 15 is a bit high since that many cards cannot fit in the right gramplet sidebar without scrolling. That scrolling means that access to switching between the Categories is impeded.

And in the Tabbed configuration, I cannot access icons for the tabs that are off-screen to the right. There is no scroll ">" gadget like what appears in the Sidebar when too many gramplets are loaded to be shown.

**Comment by cdhorn** [comment]
> But it appears that this Gramplet shares data amongst its iterations? So it only needs to poll if the tree has been "Dirty"d, otherwise it load from a common cache?

Yes, it uses a singleton service to handle the tracking.  It connects to the db object signals, so after the initial load it should just be incremental update and it doesn't need to scan the whole database again.

I will lower the default to 10.  My screen comfortably fits about 20, it is hard for me to judge sometimes.

In tabbed mode the Gramplet itself is in a scrollable window if you go to bottom you will see slider pop up.  I would like to find a way to make the tabs smaller and more compact but was not able to find a way. Maybe someone more knowledgeable knows how.

Hmm... maybe the stack widget or a toolbar would work better.
