### ISSUE TITLE
Add optional support for pivoting focus to newly added objects

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/CardView#138]
Make configurable based on type and maybe context if not too difficult. If adding a note or citation probably does not make sense to shift, but if adding a new person or family it may.

**Comment by cdhorn** [comment]
Actually this probably only makes sense when adding a completely new object using the toolbar and not something in relation to something else.

**Comment by emyoulation** [comment]
True. And it happens more rarely once you develop efficient workflows. 

These days, I tend to create new records within the structure that already relates them to another primary or secondary object. So I'll add a spouse, parent, or child; not an isolated person which has to then be connected to the family tree.

So newbies are the most likely to be affected. And people getting their feet wet with a new GUI. So having something like this might not be necessary later but will reduce the number of early abandons.

Yet I often accidentally close the multitude of spawned Edit Object dialogs out of order. And core Gramps has a [bug](https://gramps-project.org/bugs/view.php?id=12008) where it pops a warning suggesting that save changes in the spawned windows and then save the record without doing the secondary object connection. Effectively orphaning the newborn object.

There are other scenarios where tracking new objects is useful... like how frequently sharing that record will be repeated immediately in the session. (Such as when adding a new Cemetery or Source. Most likely, you will be using that new Place or Source for several immediate relatives in the next few minutes.)

**Comment by cdhorn** [comment]
Closing this. Focus doesn't shift for events and repos but the code is there. The editors do not seem to be calling the callbacks so that would be a core code issue to debug. May visit that in 5.2 eventually.
