### ISSUE TITLE
Configure window size

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#146]
The default window size for the Configure is not wide enough to display all the columns. (And there's extra space to the right of the Buttons.

![image](https://user-images.githubusercontent.com/69127217/170508523-899d5ee1-8460-41cb-9a2d-e0d39752c2f3.png)

![image](https://user-images.githubusercontent.com/69127217/170507548-94082e29-4438-4443-b389-9eef3078691e.png)

**Comment by cdhorn** [comment]
Help button added, can repoint urls later. The URL's are in src/view/config/config_const.py at moment but probably move again.
