### ISSUE TITLE
Help button for Configure dialogs

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#147]
The Configure templates are a new Core Concept within Gramps.  Please add help buttons (and translatable help_URL ) for the dialogs.

Initial URL could be to a new "Configuration" section header in the README.md just above the "Coloring Schemes" subsection:
https://github.com/cdhorn/CardView/blob/master/README.md#coloring-schemes

**Comment by cdhorn** [comment]
Yes we'll figure something out with this and the wiki.

**Comment by cdhorn** [comment]
Initial iteration done.   Breakdown of the help pages will be:

Addon:CardView
Addon:CardView Configuration:Global
Addon:CardView Configuration:Layout
Addon:CardView Configuration:Active
Addon:CardView Configuration:Groups
Addon:CardView Configuration:Timelines
Addon:CardView Configuration:Colors

Can easily change later if documentation team wants something different.

**Comment by fxtmtrsine** [comment]
FYI a few people have already edited the wiki support page with the following comments:

>  [addon links are not resolving here and need to be adjusted in addon](https://gramps-project.org/wiki/index.php?title=Addon:CardView&curid=17903&diff=92157&oldid=92156) eg https://www.gramps-project.org/wiki/index.php/Addon:CardView_Configuration:Templates is wrong wikiformat for url

the adjusted full working links are:

* Addon:CardView Configuration:Global
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Global

* Addon:CardView Configuration:Layout
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Layout

* Addon:CardView Configuration:Active
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Active

* Addon:CardView Configuration:Groups
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Groups

* Addon:CardView Configuration:Timelines
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Timelines

* Addon:CardView Configuration:Colors
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Colors

also the following one is for the help button on the Configuration:Templates page
https://gramps-project.org/wiki/index.php/Addon:CardView#Configuration:Templates



Also see suggestion on help for context menu's
https://github.com/cdhorn/CardView/issues/162

**Comment by emyoulation** [comment]
These URLs are in transition. The CardView Configuration documentation  will be spun out from the Main page to segment the load on the Gramps project server. The main page will have a huge number of screenshots. As the Configuration will have another huge set. Separating them will make the pages load faster too.
