### ISSUE TITLE
CardViews allow Printing or exporting to SVG?

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#151]
Not a bug more like a feature request for the ability to print the CardViews ( or optionally exporting to an SVG file? )

So far I've be screenshotting  the pined card views.

Brilliant add-on by the way 🥇

**Comment by emyoulation** [comment]
Duplicate of [issue 108](https://github.com/cdhorn/CardView/issues/108).

That suggestion/comment was closed because it is "out of scope" for the 1st release.

**Comment by fxtmtrsine** [comment]
Ok fair enough closing , thanks for the addon @emyoulation 👍
