### ISSUE TITLE
Future feature? Also add the "Person" CardView to the "Relationships" category view

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#152]
Please consider duplicating the "Person" CardView in the "Relationships" category view also for the obvious (to me sorry 😊) reason that it is an alternate relationship view.

Thank you

**Comment by cdhorn** [comment]
This might complicate some things, I have not thought about it.  I will give it a shot and see. The current navigation mechanism would not include it in the history, you would get sent to the person page.

**Comment by cdhorn** [comment]
Yes, seems fine, behaves as thought it would. Added in 347eb11e2a4c68a59ff5edcbd06d41ebdda12ec7

**Comment by fxtmtrsine** [comment]
Thank you 🥇
