### ISSUE TITLE
Indicators are too hard too discriminate 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#155]
My vision is poor (and genealogy tends to be a hobby of older folk), could CardView have an icon size configuration to use (Toolbar sized) 24x24 icons instead of tiny 16x16 size? (Or whatever the next size up is.)

Probably in the same place that you can turn Status & Child Object Indicators off completely.
Child object indicators.
![cardview-indicators-child-objects](https://user-images.githubusercontent.com/69127217/170706252-efd1269d-8529-4de5-894d-6faa0c9a173d.png)
![cardview-indicators-status1](https://user-images.githubusercontent.com/69127217/170706286-f0a5985c-11a0-4c31-86a2-a82b17be23c2.png)

**Comment by cdhorn** [comment]
This is done. Also for people with zillions of tags added option to set a max number of them to display.
