### ISSUE TITLE
Could the Configure Template Editor be refactored to become the Dashboard view CardView mode?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#158]
I had a strange thought.  Adding a CardView view mod to the Dashboard view may be a way to de-mystify some of the Configuration functionalities. 

The Template Editor is pretty much a Dashboard control for all the CardViews.  You could move it there (with an overarching Template selector row at the top) and reduce the Configure in Each view mode to simply the Template selector.

You might also have a diagnostic selection for that dashboard view mode (or a configuration of it) which echos your console messages like:
`render_page: I0000044 3.7113418579101562

 (I've always felt the Dashboard is underutilized for such a prominent spot in the GUI.  Additional Dashboard viewmode configurations to augment the Default "Welcome/Introductory" set of Gramplets make a lot of sense: there could be a sets optimized for: Database heath, Data entry, Report generation, research. You may find that moving the Sidebar.ini and Bottombar.ini for your CardView to your template manager might make sense in the same way.  You might want a set of Minimals templates coupled with data entry Gramplets for transcription sessions, another set of Defaults with preselected Chart, biography & similar Gramplets for exploration.)
`

**Comment by cdhorn** [comment]
I have no plans to do anything with the Dashboard at the moment.  I DO have some thoughts about things that might be done, and you just added to them a little, but I'd rather keep that out of this at the moment. 

Templating things managed by core Gramps code would have to be evaluated if this or part of this work is folded in at some point.

**Comment by emyoulation** [comment]
Sorry to add to the pressure. I'll try to curb my enthusiasm.

No promises though... I'm pretty excited.
