### ISSUE TITLE
Not all Indicators show a count when "[x] Enable display of object counts with the indicators icon" selected

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#159]
Testing the indicators and found that when  _Global/Basic Indicators/Child Object Indicators/_"**[x] Enable display of object counts with the indicators icon**" is selected not all Indicators (Citation Alerts & Notes in screenshot) show a count.

![2022-05-28 09_41_23-Window](https://user-images.githubusercontent.com/32380545/170801952-dde341ab-62ed-44df-824b-21f7b38b0019.png)
![2022-05-28 09_41_29-Window](https://user-images.githubusercontent.com/32380545/170801950-5c1605bc-8764-4a02-91dd-1278bc01a1eb.png)

**Comment by cdhorn** [comment]
That option is under child object indicators, so it does not apply to status indicators.

**Comment by fxtmtrsine** [comment]
>  That option is under child object indicators, so it does not apply to status indicators.

ok, so the status indicators don't have that option, or what I should I be looking for please?

**Comment by cdhorn** [comment]
I guess I am unsure of the question.

The icon status section contains the "status" indicators which have a plugin interface, the "child object" indicators which that option to include the count of child objects applies to, and then the "tags" as they are indicators as well in a sense.
