### ISSUE TITLE
Nav Gramplet: Name display preference changes are not recognized

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#164]
The Person display does not recognize changing of the Name display format. The change is not applied until Gramps is restarted

Date format preference changes require a restart of Gramps. (Not sure why) So they are not currently an issue.  However, if making the Gramplet recognize Date format preference changes is possible, then it would be better than other parts of the program.

**Comment by cdhorn** [comment]
Ah good catch, thanks!

**Comment by cdhorn** [comment]
Same issue applies to place format.

**Comment by cdhorn** [comment]
Should be picking up both name and place format changes in a0abf2a005c23ee5656099be7cee07efd5226611
