### ISSUE TITLE
Nav Gramplet: default Icon size

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#165]
The small icon option offer zero screen savings in the list since each card has 2 rows of info.

In the tabs/toolbar is only saves a few pixels for the entire gramplet.

**How about defaulting to 24x24 ?** (There are 4 sizes in GTK:  16px, 24px, 32px, 48px. Could the size labels be: Small, Medium, Large, Extra Large ? That doesn't mean you'd have to include support Large or Extra large. Just change the existing label from Small and Large to Small and Medium.)

Or you could use a [horizontal scale GTK gadget](https://docs.gtk.org/gtk4/class.Scale.html) and eliminate the size labels entirely:
![image](https://user-images.githubusercontent.com/69127217/170882199-48d161a8-1378-4244-9873-af8fa9999f4a.png)

From https://valadoc.org/gtk+-3.0/Gtk.IconSize.html :

[BUTTON](https://valadoc.org/gtk+-3.0/Gtk.IconSize.BUTTON.html) - Size appropriate for buttons (16px )
    [DIALOG](https://valadoc.org/gtk+-3.0/Gtk.IconSize.DIALOG.html) - Size appropriate for dialogs (48px )
    [DND](https://valadoc.org/gtk+-3.0/Gtk.IconSize.DND.html) - Size appropriate for drag and drop (32px )
    [INVALID](https://valadoc.org/gtk+-3.0/Gtk.IconSize.INVALID.html) - Invalid size.
    [LARGE_TOOLBAR](https://valadoc.org/gtk+-3.0/Gtk.IconSize.LARGE_TOOLBAR.html) - Size appropriate for large toolbars (24px)
    [MENU](https://valadoc.org/gtk+-3.0/Gtk.IconSize.MENU.html) - Size appropriate for menus (16px).
    [SMALL_TOOLBAR](https://valadoc.org/gtk+-3.0/Gtk.IconSize.SMALL_TOOLBAR.html) - Size appropriate for small toolbars (16px).

**Comment by cdhorn** [comment]
The SMALL and LARGE Toolbar are the only two I intend to support.  I may change the default once the "tabbed" style mode is done getting sorted and I see how it looks.

**Comment by cdhorn** [comment]
Yeah decided to change the default... in a0abf2a005c23ee5656099be7cee07efd5226611
