### ISSUE TITLE
Redundant text in Configuration labels

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#166]
One of the redundant words on both the left & right of the control could be eliminated
![image](https://user-images.githubusercontent.com/69127217/170881602-d90241c2-f559-4a67-8fdb-0b152829ad51.png)
Suggest that the "Use" "Show" on the left side be eliminated
the "Maximum object to display" Could be "Row count"

**Comment by cdhorn** [comment]
This has to do with the plugin Gramplet option handling which is in Gramps core.  If you check some other Gramplets with options, like Pedigree, you see the same behaviour.
