### ISSUE TITLE
Nav Gramplet: Note tracking expander or tab state on redraws

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#167]
Saving the Configuration on the Nav Gramplet collapses any expanded grouping

(sorry for the title of this issue.  Finger slipped and committed while still typing the label.  It should have been "Nav Gramplet Configuration: Collapsing saves" )

**Comment by cdhorn** [comment]
Yeah I need to check and save state before a redraw and reset after still.

**Comment by cdhorn** [comment]
Fixed with 5882ddb3618ce75ba3492a3c837ef2e55f97868c
