### ISSUE TITLE
Nav Gramplet: help_url destination

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#168]
In the [registration file](https://github.com/cdhorn/CardView/blob/master/src/recent_changes.gpr.py), the Current help_url is 
`    help_url="RecentChanges",`
please change to
`    help_url="Addon:Recent_Changes",`

Two changes:
* Harmonize with standard "Addon:" webpage name prefix
* add a Space to the webpage title

**Comment by cdhorn** [comment]
Fixed in a0abf2a005c23ee5656099be7cee07efd5226611
