### ISSUE TITLE
Card views: The RecentChanges Gramplet reflects the Themes add-on font size changes but the view modes do not.

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/CardView#170]

**Comment by cdhorn** [comment]
Font size change seems to be working okay for me on Fedora. Will need to check Windows.

**Comment by cdhorn** [comment]
@emyoulation can you check with latest if this still issue?  I added something to catch the font-changed signal to force a redraw so it should work now if it was not...

**Comment by emyoulation** [comment]
Resolved in Version: 0.97
Thank you

Could you refresh the menus when adding a bookmark?  I bookmarked 2 siblings from the Person CardView and they did not appear in the Bookmarks menu until changing the focus Person

**Comment by cdhorn** [comment]
Opened #172 for that.
