### ISSUE TITLE
relabel the "Recent Changes" gramplet

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#173]
The Gramplet does not (can not and should not) show changes... like a Diff

Could it be changed to a name of "Last Changed" to be more representative of functionality?  This also matches an already translated string too.

**Comment by cdhorn** [comment]
You forget we already have a LastChange aka "Latest Changes" Gramplet. It was the starting point for this one.

**Comment by emyoulation** [comment]
Yes, the original "Latest Changes" was a misnomer.  And if it had been named after the "Last Changed" Column Header in the list views, then it would not have added an extraneous string to the more than 5,000 string translation glossary.

I hope and believe that the original Gramplet should be retired for 5.2 and replaced with your new creation. The original can be migrated to be part of the example code package.

**Comment by cdhorn** [comment]
I am unsure if we should have two that have such similar names. But yeah it would make sense to use the same name as the list view column to be consistent.

**Comment by emyoulation** [comment]
I can raise the prospect of retiring the "Latest Changes" for 5.2 release. Having yours in circulation for a couple months before that will help.

There are extra reasons for retiring the original.  It shows in the Plugin Manager & Add menu as "Recent Changes" but shows up in the interface as "Latest Changes". In the Addon List in the wiki, it is "[Last Change](https://www.gramps-project.org/wiki/index.php/Addon:LastChange)" and the archive file is "[LastChange.addon.tgz](https://github.com/gramps-project/addons/blob/master/gramps51/download/LastChange.addon.tgz?raw=true)"

As you are painfully aware, addon names evolve during development. Finding and harmonizing all the instances has not been our most successful project.

**Comment by cdhorn** [comment]
The "Recent Changes" you see is the new one.

Jakim bundled his Last Change report in with his earlier iteration as well.

**Comment by cdhorn** [comment]
Decided I am scraping the expander mode, the stack switcher is just far superior.
