### ISSUE TITLE
Future feature request: list the Citation Alerts as a Panel in the Citations column.

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#178]
see the [discussion in the Discourse forum](https://gramps.discourse.group/t/grapview-et-combined-view/2474/12)
![image](https://user-images.githubusercontent.com/69127217/171004835-f7f8ddc3-0e5d-4d17-a0fa-73e622aa7126.png)

**Comment by cdhorn** [comment]
A request like this makes me think that perhaps the groups should be abstracted as plugins.

**Comment by cdhorn** [comment]
I suppose the status indicator icon should really pop up on the event card lacking the citation as well not just on the top level person.  And it should be extended to support family and event as top level objects.

For event it is kind of hard, supporting citations for participants belong on the event reference not the event itself.

**Comment by cdhorn** [comment]
Going to close this out as I added an Uncited Events group. A bit different from some more compact listing but it sort of fills the need I think...
