### ISSUE TITLE
Import Template odditities

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#179]
After bunging together a "Selfish" template to support a user question, I wanted to Share it on the forum. (Will there be a problem importing a template that I strip of extraneous commented fields?)

My first opportunity to share templates made me aware of a number of problems:

* When importing a template found on the desktop, a **duplicate** of the `.ini` file is incorrectly created in the same folder (with an extra `.ini` appended to the filname) in ADDITION to the .ini correctly created in the Gramps User Directory.
* Import fails silently if the Name entered for the template is invalid. 
* Template names with spaces are invalid
* The Remove button is REALLY ambiguous. Is it removing the selected or the highlighted template.  
* The dimming of the Remove was being very Odd. It was dimming when the created  template I wanted to remove was highlighted, selected or highlighted&selected. But it was undimmed when the Default & Minimal templates appeared to be the target. I had to delete EVERY cardview .ini in the gramps51 folder to get it to start working right. It appears to have the index for the templates fouled up because 1 .ini had been deleted int the OS.
* Could a Handle be added to the the header for each template and CardView start using a handle instead of an index for the template identifiers? 
* We are not going to be able to "Share" `.ini` fileypes.  I had to ZIP it to attach here on GitHub, in Discourse and to upload it to the MediaWiki system. Could the Import Template file manager access ZIPs too?
* The Import Template file manager has an "[untitled filter](https://docs.gtk.org/gtk3/class.FileFilter.html)". It needs a title.
* To disambiguate .ini files found in folders & emails, Save of the .ini files need additional comments at the top or the [template] chunk moved to the top.
I hand-inserted the following comment at the top of mine below your standard top comments:
```
;; CardView_template_Selfish.ini
;; "Selfish" Template for People view Person CardView mode 
;; posted by Emyoulation on the Gramps Discourse forum
;; see https://gramps.discourse.group/t/grapview-et-combined-view/2474/12
```
But the template chunk contained some of this:
```
[template]
active_defaults='Default'
;;base_description='Default view template'
;;base_lang_string='Default'
;;base_xml_string='Default'
name_description='Default view template'
name_lang_string='Selfish'
name_xml_string='Selfish'
normal_defaults='Default'

```

[CardView_template_Selfish.zip](https://github.com/cdhorn/CardView/files/8799112/CardView_template_Selfish.zip)

**Comment by cdhorn** [comment]
This is good feedback.  The whole template concept and handling of them needs more refinement.

**Comment by cdhorn** [comment]
> To disambiguate .ini files found in folders & emails, Save of the .ini files need additional comments at the top or the [template] chunk moved to the top.

I agree it would be useful. The existing ConfigManager code doesn't support this, so I'd need to manipulate and rewrite it after every save. I'll give it some thought.

**Comment by cdhorn** [comment]
> When importing a template found on the desktop, a duplicate of the .ini file is incorrectly created in the same folder (with an extra .ini appended to the filname) in ADDITION to the .ini correctly created in the Gramps User Directory.

I have to say as I refactored I wondered why I did what I did the way I did it...

> Import fails silently if the Name entered for the template is invalid.

I forgot to check prior behavior. The import at moment does some sanity checks to make sure it looks like a valid template. You should get error messages if it is not.  Once accepted you are prompted for a new template name. If you cancel out of that, you are cancelling the import same as if you cancel out of the file picker.

> Template names with spaces are invalid

Yes I am mandating single word template names at the present time. I might change that yet.

> The Remove button is REALLY ambiguous. Is it removing the selected or the highlighted template.

I removed the remove, we only need delete.  The new code scans the templates directory and anything found is made available in the editor. Also removed the edit attributes or whatever I had called it, those are under a tab in the Global config panel for the template.

> The dimming of the Remove was being very Odd.

I think will behave better now.  Note Delete should be dimmed if you have selected Default. I forgot to test deleting minimal, but it should just reload a default template next time it scans for template plugins.

> Could a Handle be added to the the header for each template 

I considered a uuid but decided against it.

> Could the Import Template file manager access ZIPs too?

Maybe in the future or if someone else wants to contribute the code for it.

> The Import Template file manager has an "untitled filter".

Forgot to look at that. If I recall I didn't set any filter as no idea what the user might call the one they are importing and it might not end in .ini but still be valid.

> .ini files need additional comments at the top

I have added comment support. Editing the description or the comment are now done on the Template Data tab under Global options. The comment is saved in list format in the template section and then a wrapper rewrites the file after a save to embed them in the header.
