### ISSUE TITLE
Suggestion (Configuration>Template) Button order reorganziation?

### ISSUE THREAD

**Issue by wroldwiedbwe** [cdhorn/CardView#181]
Might be just me but I keep finding my automatically hitting the first button when I really need the forth button.

Suggested order:
* Edit Template
* Edit Attributes    <###  This might be better named as "Rename Template" as Attributes are something different in Gramps?
* View Changes
* Copy Template
* Remove Template
* Delete Template
* Import Template
* Help

Maybe also add a line or heading at the top that mentions the templates relate to the CardView, as no mention is currently visible only shows "Preference Templates"  so how about "CardView Preference Templates" same probably goes for the "Template Change View"?

Fyi since you have now added the great "Recent Changes" gramplet  when you go to configure the cardview the "Recent Changes" tab is shown first instead of the "Templates" tab proably another reason to call it something meaningful like "CardView Templates"?

![cardviewbuttonorder-existing](https://user-images.githubusercontent.com/29416263/171071932-519955be-dbe4-47b2-bd92-a32a1c5bcea1.png)

**Comment by cdhorn** [comment]
Thanks for the feedback!  When time permits the template stuff needs some work and I will keep this in mind.  And you are right, I should qualify them in some way as they are only used by the view and are not a global construct.

**Comment by cdhorn** [comment]
Agreed with you on this, just reswizzled them.
