### ISSUE TITLE
Gramps(Not Responding) Person CardView - Fixed by removing  "Recent Changes" gramplet

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#184]
Finding that I get the message "**Gramps(Not Responding)"** in the program titlebar  and everthing goes grey when I select the Person CardView, I identified/fixed it by removing  "Recent Changes" gramplet  , maybe the gramplet could be delayed evaluating the recent changes?

**Comment by cdhorn** [comment]
How large is your tree?

**Comment by fxtmtrsine** [comment]
> How large is your tree?

14563 people.

**Comment by emyoulation** [comment]
Maybe the queries could be made lighter & smarter on refreshes?

That is, after the initial slow read (or any time the Configuration "Maximum objects to display" is not increased, then maybe you could use the timestamp of the oldest "last changed" in each category in the Query? 

The only place I could see that failing is if the changes were record deletions. Against that case, if the returned record count wasn't enough to file the list, you could run a less aware query.

**Comment by fxtmtrsine** [comment]
The original last change gramplet works and looking at the [code](https://github.com/gramps-project/addons-source/blob/0a8d149a6896d5e183faff0b9d009ee4a81d7701/LastChange/LastChangeGramplet.py#L70)  and the [recommendation](https://gramps-project.org/wiki/index.php/Gramplets#Core_Methods) on the gramps wiki the yield function that releases the gui ( **# let rest of GUI run** )has been [removed in your version of the gramplet](https://github.com/cdhorn/CardView/blob/master/src/last_changed.py)

**Comment by cdhorn** [comment]
Yep I was just writing that in my response and you posted.

Jakim was using yield in there but that was new to me and I pulled that out to get things working but did not back track to work it back in.  I will need to do so.

**Comment by emyoulation** [comment]
There's another option.  Most systems use multi-core processors now but Python tends to restrict itself to the 1st 2 cores. (

**Comment by cdhorn** [comment]
So this is somewhat fixed after doing some homework.  Yield helps to a point, but with very large trees it still takes a while.

The proper fix really is to index the change field and query the database.

I did add some visual feedback at least that it is doing something so it doesn't sit with a blank panel. I considered outputting what number it had processed along the way but that just slows things down more so only update it when parsing a new category.
