### ISSUE TITLE
RestoreHist Warning on switching 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#185]
After just loading the Example.tree (swapping out my 45,000 person tree), I was switching via views the Navigator bar: from the Relationships standard view mode to the People Person CardView mode. Perhaps it was passing a bad signal?

The following Warning went to the Console (not the GUI)

```
Warning: GlobalHistory: Signal emitted with wrong arg types: active-changed
         from: file: C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\RestoreHist\restorehist.py
               line: 59
               func: clear_history
    arg passed was: ['Person', 'GNUJQCL9MD64AM56OH'], type of arg passed <class 'list'>,  type should be: <class 'tuple'>
render_page: I0000044 5.375149965286255
```

**Comment by cdhorn** [comment]
Yes, the RestoreHist add on does not preserve the tuple for the new navigation class as json.dumps converts to a list and it gets read back in as a list.  This can safely be ignored. 

I am going to submit a patch for Paul for it when I get around to it, so I guess I'll leave this open as a reminder till I do.

**Comment by cdhorn** [comment]
Going to close this one.  I opened https://github.com/gramps-project/addons-source/pull/540 against RestoreHist plugin for it.
