### ISSUE TITLE
Handling of text color

### ISSUE THREAD

**Issue by bnapolitano** [cdhorn/CardView#191]
This is somewhat related to #154.  I use linux, but I imagine what I describe is true for Win & Mac as well.

With Card View, it seems that it makes it's decision about text color based on whether the theme is light or dark rather than the background of the card.  When the theme is light, the text of the cards is always black, even if I try changing the color scheme between light and dark (under Preferences -> Colors).  When the theme is dark, the opposite is true, the text of the cards is white (or light), and it also remains that way whether the light or dark color scheme is chosen.

I was testing Gramps 5.2 and noticed that the builtin pedigree chart changes the text color to black or white depending on whether the background is light or dark.  In Gramps 5.1 the text is always black.  I ran a diff of pedigreeview.py in both versions and found a new get_contrast_color function was added.  Here's the [commit](https://github.com/gramps-project/gramps/commit/f290fd9bcf0e0197501d7998569651a28ae981ff) for reference.

I'm enjoying testing this fancy new addon, great job and thanks for all your work so far!  The Card View views look great with a light theme, but as a user that prefers dark themes, I'm hoping the get_contrast_color function might help.

**Comment by cdhorn** [comment]
Excellent suggestion, thank you!

**Comment by cdhorn** [comment]
You will be able to set default foreground color for light and dark color schemes. I have some other stuff to cleanup before I push an update upstream but it works pretty well.

**Comment by cdhorn** [comment]
Added in 5ba83f4009997da0c916e8d9dc01505b610005cc under Global, Display Options where the default background and focus can be set.
