### ISSUE TITLE
LastChanged Gramplet: No results when added to Dashboard

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#193]
No results when added to Dashboard, probably  should default to "Global" results?

![Configure Dashboard - Dashboard - Gramps](https://user-images.githubusercontent.com/32380545/173166754-2fbb1285-9429-4748-8ffe-8fc2c6e99ca3.png)

**Comment by PQYPLZXHGF** [comment]
I see this and also and get the message:

> WARNING .Db: database is closed
> **WARNING .Gramplets: Gramplet gave an error: Last Changed**

![Gramps Warnings](https://user-images.githubusercontent.com/212355/173169960-d75bd7ab-96cd-46dd-bbfe-8dbc5ad87c02.png)

**Comment by cdhorn** [comment]
Oh I didn't even think to try that.. sorry.  Yes I agree setting default to Global makes the most sense there.

**Comment by fxtmtrsine** [comment]
>  Yes I agree setting default to Global makes the most sense there.

Ok 👍 thanks.

The word Global in English trips me as I thought it meant "of or related to the world / relating to or encompassing the whole of something, or of a group of things.",  how about changing the icon tooltip to "All" or ""All changes", I was going to suggest "All results" but for changes it does not sound correct to me?

@PQYPLZXHGF Thanks I see the same warning 👍

**Comment by cdhorn** [comment]
How about "All objects"?
