### ISSUE TITLE
ToDo Indicator: Should be able to filter out ones tagged as complete

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/CardView#195]

**Comment by emyoulation** [comment]
Would completed "ToDo" notes have their Type converted?

I change mine to a "Research Log" and set the Privacy flag. (Can be done en masse with SuperTool.) In general, the ability to filtering out 'Private' objects would be useful.

Having the ability to calculate a Flag would be nice though. I just do so with SuperTool. (i.e., Tag all Persons with a burial event and a FindAGrave citation.)

**Comment by cdhorn** [comment]
I'm not sure in general what other people do, if they convert the type or just add a complete tag.

**Comment by cdhorn** [comment]
Decided not doing anything with this, closing it.
