### ISSUE TITLE
Show the section titles when sections are collapsed & provide a toggle to show/hide all.

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#200]
For all cards show the section titles when sections are collapsed & provide a toggle to show/hide all.

When you collapse a section 
![2022-06-15 15_16_17-main - Tag - Gramps](https://user-images.githubusercontent.com/32380545/173743903-23f4d725-b9e7-4f8c-aa49-d3a7cb9df432.png)

you get this which I find not very useful.

![2022-06-15 15_16_32-main - Tag - Gramps](https://user-images.githubusercontent.com/32380545/173743898-be032491-c023-42f6-a83b-47e1e097374c.png)

(originally mentioned in https://github.com/cdhorn/CardView/issues/196#issuecomment-1156003215 )

**Comment by emyoulation** [comment]
> you get this which I find not very useful.

Retaining a header for a collapse would mean that the column width would not collapse with the collapse of it's last section. So collapsing would not recover space to widen the other, uncollapsed columns.

Perhaps you can suggest an alternative that does not sacrifice the horizontal space?

**Comment by cdhorn** [comment]
I disabled the expander wrapper altogether and that does in many ways look and feel cleaner.

The main reason it was added way back for the groups was so in person view I could quickly roll up the children and not have to scroll down when there were multiple spouses and so I had some kind of label for the group.

Perhaps that needs rethinking.

**Comment by wroldwiedbwe** [comment]
@fxtmtrsine Have to agree looks bad lets avoid [MMN](https://en.wikipedia.org/wiki/Mystery_meat_navigation) in Gramps! 

As it stands you can't tab or move around the card views using keyboard shortcut like the reset of Gramps so maybe keyboard shortcuts could be used to [toggle](https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Keybindings#All_List_Views_bindings)  sections and like in list views use the context menu to expand or collapse all nodes?

![People Tree View - Gramps](https://user-images.githubusercontent.com/29416263/174310114-2ec171e5-26c5-40ba-9adf-e98044c984ac.png)


Does it bother anyone else that the section titles are repeated inside the section statistics cards? If section titles are to be always shown then you could remove the repeated title.

**Comment by cdhorn** [comment]
Global -> Display -> Last option on bottom is Group wrapper display mode so people can tailor as they please with 5 modes to select from. Child groups will always have an expander though, but when collapsed will show the group title. Also removed the titles on the statistics cards.

Adding an expand all / collapse all isn't something I personally need so don't plan on spending time on. If someone wants to submit a PR to add it I'd have no problem doing so though.
