### ISSUE TITLE
Last Changed background too stark as White

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#201]
The background color of the Gramplet would be better if it used the background color of the view. And the background colors for the tiles in the object type from the CardView mode too.

Seems like the lighter grey border color for the Events column would be less strident for the Last Changed gramplet tiles. This would increase the contrast of feedback for the current bold black outlines for the Rollover effect. 

![image](https://user-images.githubusercontent.com/69127217/174345523-bf62b051-8cd8-4574-b553-3f7591628370.png)

**Note:** there is a problem with the width of the tiles.  The right rounded edge doesn't appear until the width of the sidebar is expanded to be about 2x the width of the content.

**Comment by emyoulation** [comment]
The other thing that does not conform with the CardViews is that the tiles have no vertical spacing between.  So the borders butt up against each other and leave no room for any theme effects (like 3d effects of shadows and lightened edges.)

**Comment by cdhorn** [comment]
Closing this as Gramplet is standalone now. At moment no plans to change or enhance it either.
