### ISSUE TITLE
How can the Dashboard stats be re-recalculated?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#203]
Noticed 3 each "Unknown" roles for People & "None" roles for Families.  (Thank you for adding that section!) Corrected the 4 incorrect roles.  

However, the stats remained unchanged after Events were modified. And I could find no place to force a rescan.
Perhaps a feature could be tied to the "Dirty" flag?  Where it appears if the Tree has been changed which forces new stats to be collected?

Recollecting all new stats on every Dirty might be excessive.

**Comment by cdhorn** [comment]
Per #192 that is still on the todo list.

**Comment by cdhorn** [comment]
Added a refresh stats button to manually trigger a rebuild.

**Comment by cdhorn** [comment]
Refresh button now disabled once stats loaded, and if something in db changes then it should be enabled again to give a visual cue that the stats are stale.
