### ISSUE TITLE
Discussion on possible improvement to Person card

### ISSUE THREAD

**Issue by patsyblefebre** [cdhorn/CardView#205]
@cdhorn Thanks eternally for the addon 👍 

I've been using it for about a week on and off and so far only one thing I believe needs to be improved but how I don't know exactly how so I'm raising it here to get some feedback from others.

On the Person card I believe the display and handling of the way the "Parents and Siblings" and "Spouses and Children"  (section?)  are shown when the person is in more than one family or has had multiple spouses and children should be improved?

![](https://user-images.githubusercontent.com/107233751/176084741-097e3a81-bd20-414c-ac6c-ddbe8ba01db7.png)

_I modified my example.gramps file to have above displayed._

* "Parents and Siblings" section  - Biological / Half siblings / Unrelated siblings (from parents other marriage)?

* "Spouses and Children"  (section?)  - unless you collapse the Children section you don't see any indication of the other partners ?

**(Work in progress; I add more to this as I think about it.)**

**Comment by cdhorn** [comment]
You're welcome.

Commit 6d333c800e91d63d6ecd48dab51566dee15854fe adds family count to the group label if there are more than one present.

**Comment by cdhorn** [comment]
Let me know if you think the label change is sufficient.  I could add options to not expand siblings/children if needed when rendering but I think the label should do. 

Also if any other ideas have come to mind.

**Comment by patsyblefebre** [comment]
> Let me know if you think the label change is sufficient.

Yes that did the job well.

Thank you
