### ISSUE TITLE
What else can we do to help you?

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#207]
What is the next step for this addon so that general users can access it?   Will you be submitting it to gramps addons to be released?

**Comment by cdhorn** [comment]
I do plan on finishing getting it ready and folding it into the addons.  This past month I did not have much time to work on it due to travel and other unplanned reasons but hope to pick it up again shortly once I finish taking care of some other commitments.

**Comment by fxtmtrsine** [comment]
Thanks for the update. 👍
