### ISSUE TITLE
Add default Gramplet to complement the Dashboard category "Changes" CardView 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#208]
The "[Session Log](https://gramps-project.org/wiki/index.php?title=Gramps_5.1_Wiki_Manual_-_Gramplets#Session_Log)" gramplet is a good complement to the Changes Dashboard.
It show a few additional changes ...  like Active Person focus, changing loaded databases... that that are not record modifications. But that are useful for re-tracing one's steps.

This would mean the Right Sidebar won't be blank by default. Perhaps the Bottombar can be turned off by default?

**Comment by cdhorn** [comment]
Sure, added it as a default. 

If I recall I was unable to find a way to disable the bottom bar by default.
