### ISSUE TITLE
Statistics Gramplet sub-items marker is crude

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#211]
The greater than > symbol is not an elegant look. (Reminiscent of old eMail terminal quoting)

How about using a bullet?
•

Thought about suggesting an arrowhead but GUIs often uses as a hot control for expandable/collapsible lists
‣

**Comment by TheMihle** [comment]
I agree with this.
Just having no symbol but have the amount the sub items are to the right of the main items might be an option tho, but maybe not the best one.

**Comment by cdhorn** [comment]
Agree, a bullet does look nicer.  Just pushed b7111ac20120506a1d4d9359110ae9299d9494b5 with it.
