### ISSUE TITLE
Context menu's "Edit Family" on family event

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#216]
Is it possible to call an object editor with anything other than the default configuration?

I've not seen it anywhere in the Gramps interface but...

If you right-click on a marriage event under a Family, the top item offers an Edit Family. Could that Family Editor dialog open with the 2nd tab (Events) selected instead of the 1st tab (Children)

The only other Edit Object Dialog I can recall with a similar situation is the Names tab in the Person Editor. But it might not be pertinent since I don't recall seeing an preferred/alternative Names card in CardView either. (Does a Names card option exist anywhere?)

**Comment by cdhorn** [comment]
I don't recall any arguments that can be passed to select an active tab when calling any of the editors but would need to check the code to see.

**Comment by emyoulation** [comment]
thanks!
