### ISSUE TITLE
Restarting in a remembered Family Card view

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#219]
When restarting Gramps with the Preferences set to remember the view BUT not load the last Tree, the following message appeared in the Console

```
Warning: GlobalHistory: Signal emitted with wrong arg types: active-changed
         from: file: C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\RestoreHist\restorehist.py
               line: 59
               func: clear_history
    arg passed was: ['Family', '03GKQCH37C1SL9C5B3'], type of arg passed <class 'list'>,  type should be: <class 'tuple'>
render_page: F000372 1.6110000610351562
stats collected: 10.844639301300049
```

**Comment by cdhorn** [comment]
Again, this is the RestoreHist plugin as explained a few times previously. The PR I submitted with a fix is still in queue, I've not received any feedback from Paul about it.

https://github.com/gramps-project/addons-source/pull/540

**Comment by emyoulation** [comment]
Sorry bout that chief.

Thanks for your patience
