### ISSUE TITLE
Clipboard icon in ToolBar disappears

### ISSUE THREAD

**Issue by DaveSch-gramps** [cdhorn/CardView#222]
While navigating card views I noticed that the Clipboard icon disappeared. In testing, it only disappeared when I accessed the Media card view. After navigating to other views (including standard Gramps views) the Clipboard icon did not return.

Full disclosure, I have a heavily modified tool bar. 

https://github.com/gramps-project/gramps/pull/1139

I have this PR implemented in my 5.1.5. However, even my changed icons appear as expected in all other card views so long as I have not visited the Media card view.

I did notice that the icon to "View in the default viewer" specific to the Media view is grayed out in the card view. The Clipboard icon, etc would normally appear after this icon.

Using version 0.99.110 of 23 October.

People card view

![peoplecardview](https://user-images.githubusercontent.com/61884146/197792224-e3a00182-21a1-4c93-a26e-838f898dde2c.png)

Media card view

![mediacardview](https://user-images.githubusercontent.com/61884146/197792367-9cbcb60a-0773-4aae-90f2-43b49be6b688.png)

**Comment by emyoulation** [comment]
Note that when switching the Person category view mode from Grouped to Person Card, the toolbar redraws TWICE. The Tags & Clipboard icons missing initially, then inserted.

**Comment by cdhorn** [comment]
The open media button works now.  And you submitted fix for the clipboard so think this could be closed.

I'm not noticing any double redraw behaviour but would consider that a different issue.
