### ISSUE TITLE
Feature: add "QuickView" submenu to object Context Menus

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#224]
The object context menus for the default views have an extra section divider and option at the bottom: "Quick View".  (The Person view modes may also have "Web Connections" from an Add-on. Web Connections does not currently augment other view but the documentation indicated future expansions.)

Could you enable "Quick View" menus in your object context menus?

**Comment by cdhorn** [comment]
Closing this in favor of more detailed #232 as they request the same thing.
