### ISSUE TITLE
Zotero support

### ISSUE THREAD

**Issue by JPR56400** [cdhorn/CardView#229]
> There is experimental support to import notes as well, but they are imported in raw html format. 

Adding citation in Gramps using Zotero works well. 
How can i do for testing this import notes?
Thank you Chris!

**Comment by cdhorn** [comment]
Open the preferences editor, edit template, under the global option set under general options you will find a toggle to enable the notes import.  That was very much incomplete if I recall, there were numerous issues so I set it aside.

And you're welcome.
