### ISSUE TITLE
Missing refresh

### ISSUE THREAD

**Issue by JoergHoffmannatGitHub** [cdhorn/CardView#236]
What a great tool. It will make my work much easier.

I'm using/testing CardView on Windows.
Changing some data, via CardView or via Gramps, will not update the view of CardView.

**Comment by cdhorn** [comment]
It should be catching database update signals and refreshing.  Can you describe in more detail the exact sequence of steps you took, I need to be able to reproduce it.

**Comment by JoergHoffmannatGitHub** [comment]
My first observation was to change the confidence of a citatation. The color wasn't updatetd. But after restarting Gramps it's ok, the color and text was updated.
The second observation was by making some changes in Relationship Gramps view. Add some events (edit peron, add event) and also some children (edit family, add children). After going back to the Caard view, nothing was changed. This is also not reproducible.
You can close this Bug - not reproducible.
