### ISSUE TITLE
Error when adding citation in Gramps 5.2 using Zotero 6.0.30 and plugin Cardview 0.99.110 

### ISSUE THREAD

**Issue by JPR56400** [cdhorn/CardView#241]
Adding citation in Gramps using Zotero was working well from long time. Thank you Chris!

I have read the [Gramps testing 5.2](https://github.com/cdhorn/CardView/issues/239) and Cardview 0.99.110 works.

I try to create a citation in Gramps 5.2 using Zotero 6.0.30 and plugin Cardview 0.99.110 and i have the message :

`208254: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/home/jp/.gramps/gramps52/plugins/CardView/src/view/actions/action_citation.py", line 193, in add_zotero_citation
    self.zotero.add_citation(
  File "/home/jp/.gramps/gramps52/plugins/CardView/src/view/zotero/zotero.py", line 97, in add_citation
    gsource = self.get_gramps_source(zsource)
  File "/home/jp/.gramps/gramps52/plugins/CardView/src/view/zotero/zotero.py", line 110, in get_gramps_source
    zkey = zsource["citation-key"]
TypeError: 'NoneType' object is not subscriptable`

Have you seen this error?
Thank you!

**Comment by emyoulation** [comment]
Maybe this is related to the new CITE plugin framework? And the "legacy" CITE built-in plugin?

**Comment by cdhorn** [comment]
Initial guess likely not. I really need to find a way to make some time to see where things stand now that 5.2 is out.

**Comment by cdhorn** [comment]
@JPR56400 this should be fixed, at least it is on my local setup. An update to the Better Bibtex extension appears to have made some minor changes in the response format.

**Comment by JPR56400** [comment]
Now It works ! Thank you Chris!
