### ISSUE TITLE
 If database empty and no people in it consider displaying option to enter new user to get started

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/CardView#6]
If database empty and no people in it consider some sort of welcome and click here to enter someone.

**Comment by emyoulation** [comment]
Two other special cases for which to compensate are: 
1) when NO database is loaded.  And, 
2) when there is a Tree containing People loaded but no Active Person 
(When importing a GEDCOM into a new Tree, there will initially be no defined Active Person or Home Person.)

**Comment by emyoulation** [comment]
If you come up with an approach for this, please consider if there might not be a way to make the code reusable for other View modes.

For instance, what ​should happen in the Dashboard would be different from a Person view submode if:
 ​No Tree is loaded; no Gramplets are docked; no death is in a loaded tree.

But the View should still give some push towards making itself productive.

Maybe it could be something as simple as textbox being overlaid on the View backdrop suggesting a 'next step' corrective action. (But no pop-up dialogs!).

**Comment by cdhorn** [comment]
Decided this is out of scope for now, closing as unimplemented.  If the view is added to Gramps core at some point maybe revisit.
