### ISSUE TITLE
Sidebar/Bottombar Gramplets list incomplete for Relationship view compatible gramplets

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#60]
There are only about half as many Gramplets listed in the Sidebar and Bottom bar gramplet menu for the Profile View compared to the standard Relationships or Combined modes.

With all possible gramplets downloaded, only about "A thru F" gramplets fit on my screen with the other Relationships view modes. ("F thru Z" comprise another screen-full.)  But "A thru Z" (well, it scrolls for 1 entry) fit on the Profile gramplets menu

**Comment by cdhorn** [comment]
Closing this as the refactor addresses this as the view is split across the primary categories.
