### ISSUE TITLE
Release an incremental version?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#84]
Christopher,

From you earlier postings, I'd guess that you still have a lot of outstanding targets on your ToDo list. But would you consider disabling stuff that isn't ready yet & releasing the rest as a "version 1"? 

It would be nice to have a version go through peer review and then get out into wider use.

**Comment by emyoulation** [comment]
If a release plan is in your roadmap, this issue is a bit redundant. Maybe you could close it?

**Comment by cdhorn** [comment]
Agree.
